ARG NODE_VERSION=20.12.0

FROM node:${NODE_VERSION}-alpine as base
ARG ENV=prod
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git graphicsmagick imagemagick
WORKDIR /usr/src/app

FROM base as build
COPY ./donaction-api/package*.json ./
RUN npm ci --legacy-peer-deps
COPY ./donaction-api .
COPY ./donaction-api/.env.${ENV} ./.env
RUN echo 'Environment'
RUN echo ${ENV}
RUN ls -l
RUN npm run build --ignore-prompts

FROM base as final
COPY ./donaction-api/package*.json ./
COPY ./donaction-api/config /usr/src/app/config/
COPY ./donaction-api/database /usr/src/app/database/
COPY ./donaction-api/public/ /usr/src/app/public/
COPY ./donaction-api/data/ /usr/src/app/data/
COPY ./donaction-api/src/ /usr/src/app/src/
COPY ./donaction-api/types/ /usr/src/app/types/
COPY ./donaction-api/donaction-gcc-config.json /usr/src/app/donaction-gcc-config.json
COPY ./donaction-api/.env.${ENV} ./.env
COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY --from=build /usr/src/app/dist /usr/src/app/dist
EXPOSE 1437
CMD ["npm", "run", "start"]
