export const environment = {
  env: 'prod',
  baseUrl: 'https://www.klubr.fr/admin',
  apiUrl: 'https://www.klubr.fr/service/api/',
  nextJsUrl: 'https://www.klubr.fr/',
  nextJsUrlSm: 'klubr.fr/',
  domain: 'www.klubr.fr',
  apiToken: 'XXXXXX',
  apiTokenV1: 'STRAPI_API_TOKEN_ADMIN_PROD_PLACEHOLDER',
  googleClientId: 'GOOGLE_CLIENT_ID_PROD_PLACEHOLDER',
  googleClientSecret: "GOOGLE_CLIENT_SECRET_PROD_PLACEHOLDER",
  ANGULAR_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: "GOOGLE_RECAPTCHA_SITE_KEY_PROD_PLACEHOLDER",
  GOOGLE_MAPS_API_KEY: "GOOGLE_MAPS_API_KEY_PROD_PLACEHOLDER",
  STRIPE_PAYMENT_LINK: "https://dashboard.stripe.com/payments/",
  klubrUuid: 'KLUBR_UUID_PROD_PLACEHOLDER',
  enableAnalytics: false,
  plausibleDomain: 'klubr.fr/admin',
  pwaEnabled: true,
};
