ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine as base
ARG ENV=re7
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git graphicsmagick imagemagick ghostscript
ARG ENV=re7
WORKDIR /usr/src/


FROM base as build
COPY ./klubr-api/package.json ./klubr-api/package-lock.json ./
RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install --only=production
ENV PATH=/usr/src/node_modules/.bin:$PATH
WORKDIR /usr/src/app
RUN echo 'Environment'
RUN echo ${ENV}
RUN ls -l
COPY ./klubr-api/ .
COPY ./klubr-api/.env.${ENV} ./.env
RUN npm run build


FROM base as final
COPY --from=build /usr/src/node_modules ./node_modules
WORKDIR /usr/src/app
COPY --from=build /usr/src/app ./
ENV PATH=/usr/src/node_modules/.bin:$PATH
RUN chown -R node:node /usr/src/app
USER node
EXPOSE 1337
CMD ["npm", "run", "start"]
