export const environment = {
  env: 'dev',
  baseUrl: 'http://localhost:4300/admin',
  apiUrl: 'http://localhost:1437/api/',
  nextJsUrl: 'http://localhost:3100/',
  nextJsUrlSm: 'http://localhost:3100/',
  domain: 'localhost',
  apiToken: '<!-- STRAPI_API_TOKEN_ADMIN_DEV_PLACEHOLDER -->',
  apiTokenV1: '<!-- STRAPI_API_TOKEN_V1_ADMIN_DEV_PLACEHOLDER -->',
  googleClientId: '<!-- GOOGLE_CLIENT_ID_DEV_PLACEHOLDER -->',
  googleClientSecret: '<!-- GOOGLE_CLIENT_SECRET_DEV_PLACEHOLDER -->',
  ANGULAR_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: '<!-- GOOGLE_RECAPTCHA_SITE_KEY_DEV_PLACEHOLDER -->',
  GOOGLE_MAPS_API_KEY: '<!-- GOOGLE_MAPS_API_KEY_DEV_PLACEHOLDER -->',
  STRIPE_PAYMENT_LINK: "https://dashboard.stripe.com/payments/",
  klubrUuid: '14cec9f0-a43b-4495-a890-93d52c6dea6c',
  enableAnalytics: false,
  plausibleDomain: 'donaction.fr-local/admin',
  pwaEnabled: false,
};
