export const environment = {
  env: 're7',
  baseUrl: 'https://re7.donaction.fr/admin',
  apiUrl: 'https://re7.donaction.fr/service/api/',
  nextJsUrl: 'https://re7.donaction.fr/',
  nextJsUrlSm: 're7.donaction.fr/',
  domain: 're7.donaction.fr',
  apiToken: 'XXXXXX',
  apiTokenV1: '__STRAPI_ADMIN_API_TOKEN__',
  googleClientId: '__GOOGLE_CLIENT_ID__',
  googleClientSecret: "__GOOGLE_CLIENT_SECRET__",
  ANGULAR_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: "__GOOGLE_RECAPTCHA_SITE_KEY__",
  GOOGLE_MAPS_API_KEY: "__GOOGLE_MAPS_API_KEY__",
  STRIPE_PAYMENT_LINK: "https://dashboard.stripe.com/payments/",
  klubrUuid: '__KLUBR_UUID__',
  enableAnalytics: false,
  plausibleDomain: 're7.donaction.fr/admin',
  pwaEnabled: true,
};
