export const environment = {
  env: 're7',
  baseUrl: 'https://re7.donaction.fr/admin',
  apiUrl: 'https://re7.donaction.fr/service/api/',
  nextJsUrl: 'https://re7.donaction.fr/',
  nextJsUrlSm: 're7.donaction.fr/',
  domain: 're7.donaction.fr',
  apiToken: 'XXXXXX',
  apiTokenV1: 'STRAPI_ADMIN_API_TOKEN_PLACEHOLDER',
  googleClientId: 'GOOGLE_CLIENT_ID_PLACEHOLDER',
  googleClientSecret: "GOOGLE_CLIENT_SECRET_PLACEHOLDER",
  ANGULAR_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: "GOOGLE_RECAPTCHA_SITE_KEY_PLACEHOLDER",
  GOOGLE_MAPS_API_KEY: "GOOGLE_MAPS_API_KEY_PLACEHOLDER",
  STRIPE_PAYMENT_LINK: "https://dashboard.stripe.com/payments/",
  klubrUuid: 'KLUBR_UUID_PLACEHOLDER',
  enableAnalytics: false,
  plausibleDomain: 're7.donaction.fr/admin',
  pwaEnabled: true,
};
