export const environment = {
  env: 're7',
  baseUrl: 'https://re7.klubr.fr/admin',
  apiUrl: 'https://re7.klubr.fr/service/api/',
  nextJsUrl: 'https://re7.klubr.fr/',
  nextJsUrlSm: 're7.klubr.fr/',
  domain: 're7.klubr.fr',
  apiToken: 'XXXXXX',
  apiTokenV1: 'STRAPI_API_TOKEN_ADMIN_RE7_PLACEHOLDER',
  googleClientId: 'GOOGLE_CLIENT_ID_RE7_PLACEHOLDER',
  googleClientSecret: "GOOGLE_CLIENT_SECRET_RE7_PLACEHOLDER",
  ANGULAR_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY: "GOOGLE_RECAPTCHA_SITE_KEY_RE7_PLACEHOLDER",
  GOOGLE_MAPS_API_KEY: "GOOGLE_MAPS_API_KEY_RE7_PLACEHOLDER",
  STRIPE_PAYMENT_LINK: "https://dashboard.stripe.com/payments/",
  klubrUuid: 'KLUBR_UUID_RE7_PLACEHOLDER',
  enableAnalytics: false,
  plausibleDomain: 're7.klubr.fr/admin',
  pwaEnabled: true,
};
