const TAUX_DEDUCTION_FISCALE_PART = 0.66;
const TAUX_DEDUCTION_FISCALE_PRO = 0.6;
const API_DEFAULT_PAGE_SIZE = 25;

export  {
    TAUX_DEDUCTION_FISCALE_PART,
    TAUX_DEDUCTION_FISCALE_PRO,
    API_DEFAULT_PAGE_SIZE,
};
